version = 1

exclude_patterns = [  
  "bin/**",  
  "**/node_modules/",  
  "**/*.min.js"  
]

[[analyzers]]
name = "shell"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = ["nodejs"]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"